FROM golang:1.24-alpine

RUN apk add --no-cache git
RUN go install github.com/air-verse/air@v1.61.7
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
